### ISSUE TITLE
Create Identity Modal doesn't close on creation

### ISSUE THREAD

**Issue by Schereo** [iotaledger/is-ui-components#39]
When creating a new Identity in the Identity popup modal in the Identity Manager Tab, the modal does not automatically close after the Identity was created.

Steps to reproduce:

1. Login
2. Go to Identity Manager Tab
3. Click 'Create an Identity'
4. Modal doesn't close

**Comment by dominic22** [comment]
this is intended all problems were solved in #23 and #49
